services:
  jupyter:
    build: .
    ports:
      - "8890:8888"
    volumes:
      - "/Users/home/Documents/GitHub/ADS509_2.1/ADS509_2.1/data/input:/app/data/input"
      - "/Users/home/Documents/GitHub/ADS509_2.1/ADS509_2.1/data/processed:/app/data/processed"
      - "/Users/home/Documents/GitHub/ADS509_2.1/ADS509_2.1/data/extracted:/app/data/extracted"
      - "/Users/home/Documents/GitHub/ADS509_2.1/ADS509_2.1/notebooks:/app/notebooks"
      - "/Users/home/Documents/GitHub/ADS509_2.1/ADS509_2.1/notebooks/M1 Results:/app/M1 Results"
      - "/Users/home/Documents/GitHub/ADS509_2.1/Lyrics and Description EDA.ipynb:/app/Lyrics and Description EDA.ipynb"
    environment:
      - JUPYTER_TOKEN=ads509

volumes:
  ads509_data:
  ads509_notebooks:
  ads509_m1_results:
